### ISSUE TITLE
Update for new language keywords, .bicepparam files

### ISSUE THREAD

**Issue by heaths** [Sjord/tree-sitter-bicep#2]
The last commit was made over 3 years ago, and bicep has changed a bit since then. There are some new keywords as well as .bicepparam files that replace .parameter.json files.

If there's interest in updating, could you first merge <https://github.com/the-mikedavis/tree-sitter-bicep>? That is what [helix is using](https://github.com/helix-editor/helix/blob/b90ec5c77985bd444e7043fe738bb51b396ed496/languages.toml#L2772C20-L2772C69). If so, I'd be happy to contribute some updates.

For reference, the current TextMate language file is <https://github.com/Azure/bicep/blob/main/src/textmate/bicep.tmlanguage>

**Comment by Sjord** [comment]
There is also [tree-sitter-grammars/tree-sitter-bicep](https://github.com/tree-sitter-grammars/tree-sitter-bicep). Would that work for you? That does seem to be better maintained.

**Comment by heaths** [comment]
Yes, perfect! It does seem to be fairly up to date for the official grammar, given `using` support is there: https://github.com/tree-sitter-grammars/tree-sitter-bicep/blob/0092c7d1bd6bb22ce0a6f78497d50ea2b87f19c0/grammar.js#L94.

I'll submit a PR to helix-editor/helix to update. Thanks for pointing that out!
